CircleCI-Public/mcp-server-circleci

CHANGELOG.md, package.json, src/clients/schemas.ts, src/lib/job-logs/getJobLogs.ts
Found a case where `job_number` was not present. Rather than failing validation we can filter those cases out.
=> fix: more permissive JobSchema, filter to only retrieve job when we can

CHANGELOG.md, README.md, package.json, src/clients/circleci-private/index.ts, src/clients/circleci/httpClient.test.ts, src/clients/circleci/httpClient.ts, src/clients/circleci/index.ts, src/lib/job-logs/getJobLogs.ts, src/tools/getBuildFailureLogs/handler.ts
This change enables users to configure custom CircleCI base URLs for API requests, making the client more flexible for different CircleCI deployments.
Changes:
- Add `CIRCLECI_BASE_URL` environment variable support (defaults to https://circleci.com)
- Update API clients (v1, v2, private) to accept custom base URLs
- Enhance type definitions and documentation for better developer experience
- Update README with new configuration options
Breaking changes: None
The default behaviour remains unchanged when no base URL is provided.
Documentation:
- Added base URL configuration example in README
- Updated API client documentation with new options
- Added type definitions for new configuration parameters
=> feat: Add configurable CircleCI base URL support

CHANGELOG.md, package.json, src/clients/circleci/index.ts
- Add User-Agent header 'CircleCI-MCP-Server/0.1' to identify client requests
- Bump version from 0.1.5 to 0.1.6
=> feat: add User-Agent header to CircleCI API requests

CHANGELOG.md, package.json, src/circleci-tools.ts, src/lib/mcpErrorOutput.ts, src/lib/project-detection/index.test.ts, src/lib/project-detection/index.ts, src/tools/getBuildFailureLogs/handler.ts, src/tools/getBuildFailureLogs/inputSchema.ts, src/tools/getBuildFailureLogs/tool.ts, src/tools/getFlakyTests/handler.ts, src/tools/getFlakyTests/inputSchema.ts, src/tools/getFlakyTests/tool.ts
Some bug fixes and improvements:
- fixed bug where `?branch=some-branch` in the projectURL was being considered part of the projectSlug
- consolidated both projectSlug detection functions down to just `getPipelineNumberFromURL`. added extra test cases
- changed get build logs tool to only use `projectURL` instead of `failedPipelineURL` or `failedJobURL`
- updated the tool descriptions to better describe the accepted urls
- removed now unneeded error handling wrapper
- build logs tool will now use the `?branch=somebranch` query param to find the branch if given in the url
video of the branch in url support:
https://github.com/user-attachments/assets/2598395a-453f-4198-b4f9-52e7029c5576
=> improving URL parsing, tool descriptions/schemas, branch in url

README.md
Adding claude code install instructions to the readme.
=> docs: add claude code installation instructions

CHANGELOG.md, README.md, package.json, src/circleci-tools.ts, src/clients/circleci/pipelines.ts, src/clients/schemas.ts, src/lib/latest-pipeline/formatLatestPipelineStatus.ts, src/lib/latest-pipeline/getLatestPipelineWorkflows.ts, src/lib/pipeline-job-logs/getPipelineJobLogs.ts, src/tools/getLatestPipelineStatus/handler.test.ts, src/tools/getLatestPipelineStatus/handler.ts, src/tools/getLatestPipelineStatus/inputSchema.ts, src/tools/getLatestPipelineStatus/tool.ts
- Added a tool to get the latest pipeline status
- Renamed the `getPipelinesByBranch` function in the circleci client to `getPipelines` since branch was optional
- Releasing v0.3.0
https://github.com/user-attachments/assets/5874c427-121c-493d-8b19-f0722305b953
=> feat: add latest pipeline status tool

CHANGELOG.md, package.json, src/clients/circleci-private/me.ts, src/lib/project-detection/index.ts
found an issue with our project detection logic, we were not paginating the followed projects. so if the target project was not on the first page it would be missed
=> fix: paginate followed projects

CHANGELOG.md, package.json, src/tools/recommendPromptTemplateTests/handler.ts
We must achieve a high level of consistency in the output of Circlet MCP tool calls to reliably run prompt eval/test pipelines on ANY given prompt temaplate. The prompt engineering in this PR is solely focused on achieving that consistency.
`Please find all of the AI prompts in this application and recommend tests for them.`
https://github.com/user-attachments/assets/fd2edde5-288f-4cfb-aaeb-167ff1968f95
https://github.com/user-attachments/assets/59921a82-299c-4367-a595-619476d84504
https://github.com/user-attachments/assets/dcc46a55-04aa-462b-9475-b8bd3ef83dc4
- [refactored `recommendPromptTemplateTests` handler](https://github.com/CircleCI-Public/mcp-server-circleci/commit/4ba177be0ce5f9ea1347d6846652ec59e1a51f55) to achieve a greater level of consistency in Circlet MCP tool call file …
=> refactor: `recommendPromptTemplateTests` handler for greater file output consistency

CHANGELOG.md, package.json, src/lib/project-detection/index.test.ts, src/lib/project-detection/index.ts
- Refactor `getPipelineNumberFromURL` to handle URLs without a pipeline index
- Update error message to specify project slug when getting pipeline number
=> fix: fixes #53 to handle URLs without pipelines in path

CHANGELOG.md, package.json, src/clients/circleci/tests.ts, src/lib/project-detection/index.test.ts, src/lib/project-detection/index.ts, src/tools/getLatestPipelineStatus/tool.ts
Fixes #51  the issue using Legacy Job URLs with tools.
We made a bad assumption in code if the URL is of format `https//domain.com/gh/org/project/Number" Number to be pipeline number which is actually a job number.
Now, if `jobs` is not present in the url and `pipelines` is also not present we assume the last number to be the job number.
=> fix: fixes #51 Handle legacy job urls

CHANGELOG.md, README.md, package.json, src/lib/pipeline-job-tests/getJobTests.ts, src/tools/getJobTestResults/handler.test.ts, src/tools/getJobTestResults/handler.ts, src/tools/getJobTestResults/inputSchema.ts, src/tools/getJobTestResults/tool.ts
#56 
Added the ability to filter the tests by result for the `get_job_test_results` tool.
The tool now supports the following options:
- `filterByTestsResult`: 'failure' - Show only failed tests
- `filterByTestsResult`: 'success' - Show only successful tests
The tool will now return a list of tests that match the filter.
**All tests**
**Failed tests**
**Passed tests**
=> feat: add ability to filter job tests by result

CHANGELOG.md, package.json, src/lib/pipeline-job-logs/getPipelineJobLogs.ts, src/tools/getBuildFailureLogs/handler.ts, src/tools/getBuildFailureLogs/tool.ts
implements https://github.com/CircleCI-Public/mcp-server-circleci/issues/51#issuecomment-2873879446
Support `get_build_failure_logs` to work with Url shape `https://domain.com/vcs/organization/project/job-number`
=> feat: Support legacy job urls for get build failure logs

CHANGELOG.md, package.json, src/lib/pipeline-job-tests/getJobTests.ts
#56 
Fixed `get_job_test_results` tool to filter tests by result when a job number is provided. We weren't filtering the tests by result when a job number was provided.
=> fix: fix `get_job_test_results` tool to filter tests by result when a job number is provided

CHANGELOG.md, package.json, src/lib/pipeline-job-logs/getPipelineJobLogs.ts, src/tools/getBuildFailureLogs/handler.test.ts, src/tools/getBuildFailureLogs/handler.ts, src/tools/getBuildFailureLogs/inputSchema.ts, src/tools/getBuildFailureLogs/tool.ts, src/tools/getJobTestResults/handler.test.ts, src/tools/getJobTestResults/handler.ts, src/tools/getJobTestResults/inputSchema.ts, src/tools/getJobTestResults/tool.ts, src/tools/getLatestPipelineStatus/handler.test.ts, src/tools/getLatestPipelineStatus/handler.ts, src/tools/getLatestPipelineStatus/inputSchema.ts, src/tools/getLatestPipelineStatus/tool.ts, src/tools/runPipeline/tool.ts, src/tools/sharedInputSchemas.ts
Previously these tools all would grab the latest pipeline, regardless of what branch it was. This isn't particularly useful because there could be many branches running pipelines at any time, so getting the most recent may not be work relevant to the user.
Now the tool descriptions / inputSchemas tell the LLM a branch is required, and if it is run without a branch a useful error is returned so the LLM / user knows what they need to do.
ex:
=> require branch when using projectSlug for pipeline tools

CHANGELOG.md, README.md, package.json, src/circleci-tools.ts, src/clients/circlet/circlet.ts, src/clients/schemas.ts, src/tools/analyzeDiff/handler.test.ts, src/tools/analyzeDiff/handler.ts, src/tools/analyzeDiff/inputSchema.ts, src/tools/analyzeDiff/tool.ts
Testing
===
- add unit test to the tool handler
Implementation & Technical Considerations
===
- add a new tool `analyze_diff` (a tool to analyze git diffs against cursor rules to identify rule violations)
- use dynamic discovery for the params to find git diffs and cursor rules instead of providing the rule path, rule directory from envs which requires reading files manually in the handler.
- use the rule_review logic from circlet endpoint
Screenshots/Videos
===
=> feat: analyze diff

src/tools/runEvaluationTests/handler.ts
Was seeing this error on the new eval runner script.
https://app.circleci.com/pipelines/gh/jvincent42/dummy/70/workflows/ae7c7ca4-8ef0-4117-9b4a-ad110731e140/jobs/55
```
🏎️💨  Running evaluation for template: config-assistant.prompt.yml
Traceback (most recent call last):
File "/home/circleci/project/eval.py", line 378, in <module>
main()
File "/home/circleci/project/eval.py", line 350, in main
results = run_test(template_name, api_key)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/circleci/project/eval.py", line 89, in run_test
prompt_data = load_prompt_template(template_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/circleci/project/eval.py", line 51, in load_prompt_template
with open(file_path, 'r') as f:
^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: …
```
=> chore: `mkdir -p prompts && cd prompts` on unversioned config for eval pipelines

README.md
Merging 
https://github.com/CircleCI-Public/mcp-server-circleci/pull/79/
https://github.com/CircleCI-Public/mcp-server-circleci/pull/78
as one PR. Both were approved, the difference from this PR and the above is, this is not a form from original repo
- Renaming from CircleCi API Token to **CircleCi Personal Token**
At CircleCi Platform, you can find your API token named as Personal API Tokens in User settings > Personal API Tokens.
Small change to standardize naming conventions.
- Adding routes where to find claude_desktop_config file 
As seen at https://circleci.com/blog/circleci-mcp-server/
=> Minor improvements for routes and API Token at README

CHANGELOG.md, package.json, src/tools/getFlakyTests/handler.test.ts, src/tools/getFlakyTests/handler.ts
ticket: https://circleci.atlassian.net/browse/AITEAM-658
when `process.env.USE_FILE_OUTPUT === 'true'` the flaky tests tool will output files in the current directory. this is friendlier for claude code to parse large outputs.
here is an example of one of the files that is output:
```
Flaky Test #1
==================================================
Classname: pipelines/trigger.spec.ts
Test name: Trigger a Pipeline › pipeline exists
Result: failure
Run time: 60.613
Message: trigger.spec.ts:7:7 pipeline exists
[chromium] › pipelines/trigger.spec.ts:7:7 › Trigger a Pipeline › pipeline exists ────────────────
Test timeout of 30000ms exceeded.
Error: locator.click: Test timeout of 30000ms exceeded.
Call log:
- waiting for getByRole('combobox', { name: 'Selected branch' }).first()
- locator …
```
=> add file output mode

src/clients/circlet/circlet.ts, src/clients/schemas.ts, src/tools/analyzeDiff/handler.test.ts, src/tools/analyzeDiff/handler.ts, src/tools/analyzeDiff/inputSchema.ts, src/tools/analyzeDiff/tool.ts, src/tools/shared/constants.ts
**Changes**: All changes are specific to the `analyzeDiff` tool
- **Input schema**: add `speedMode` and `filterBy` params
- **Client schema**: allow `unrelatedRules` array to be optional
- **Tests**: tweak existing tests to account for new params
- **Copy**: various copy adjustments to improve clarity
---
**Related PR**: https://github.com/circleci/prompt-template-workbench/pull/894
=> feat: add filterBy and speedMode params to analyzeDiff tool

CHANGELOG.md, package.json
**Changes:**
- Change log 
- Version bump
This is a retroactive change following the changes implemented [here](https://github.com/CircleCI-Public/mcp-server-circleci/pull/89)
=> chore: update changelog and bump version to 0.10.2

CHANGELOG.md, README.md, package.json, src/clients/schemas.ts, src/lib/flaky-tests/getFlakyTests.ts, src/tools/getFlakyTests/handler.ts
Fixed the function to properly match flaky tests by classname instead of returning all tests from jobs.
Previously, the code was collecting all job numbers and returning all failed tests from those jobs, which included irrelevant tests.
The flaky tests endpoint gives us a `test_name` on each test, which is the name of the actual test in the suite. ex `should expand the GitHub App trigger and show correct details`. This matches the `name` on the test returned when fetching from the job endpoint.
changes:
1. flaky tests request - Changed from collecting just job numbers to storing both job number and test_name
2. Match by test_name - Added logic to find the specific test that matches the flaky test's test_name within each
job
3. Fallback handling - If the exact test_name match isn't found, …
=> try to only return the relevant tests, throw an error if we cannot create the folder

README.md
The routes for Claude config file on windows and mac were under `Installation > Cursor`. Solved this by moving the routes to `Installation > Claude`
=> Fixed Claude config file routes for mac and windows.

Dockerfile, README.md, package.json, pnpm-lock.yaml, src/index.ts, tsconfig.json
Update to support implementation of CCI as a remote MCP Server using HTTP on port 8080.
In this update STDIO was replaced for a remote HTTP call on port 8080.
Also updated readme instructions including instructions for Amazon Q Developer
=> Update to support implementation of CCI as a remote MCP Server using HTTP on port 8080

CHANGELOG.md, README.md, package.json, src/circleci-tools.ts, src/clients/circleci/deploys.ts, src/tools/listComponentVersions/handler.test.ts, src/tools/listComponentVersions/handler.ts, src/tools/listComponentVersions/inputSchema.ts, src/tools/listComponentVersions/tool.ts, src/tools/runRollbackPipeline/handler.test.ts, src/tools/runRollbackPipeline/handler.ts, src/tools/runRollbackPipeline/inputSchema.ts, src/tools/runRollbackPipeline/tool.ts
The purpiose of these changes is to simplify the logic in the rollback tool and make the interactions with it more flexible.
=> [REL-4165] Splitting part of the rollback tool logic into a new list component versions tool

CHANGELOG.md, eslint.config.js, package.json, src/index.ts, src/transports/unified.ts
Fixes #125 
This PR removes all occurences of `console.log` in the MCP server. As per the [MCP docs](https://modelcontextprotocol.io/docs/develop/build-server#logging-in-mcp-servers):
> For *STDIO-based servers:* Never write to standard output (stdout). This includes:
>
> * `print()` statements in Python
> * `console.log()` in JavaScript
> * `fmt.Println()` in Go
> * Similar stdout functions in other languages
>
> Writing to stdout will corrupt the JSON-RPC messages and break your server.
This PR also extends the ESLint configuration to prevent future usage of `console.log`.
=> fix: prevent non-MCP output on stdout

src/tools/analyzeDiff/handler.ts, src/tools/configHelper/handler.ts, src/tools/createPromptTemplate/handler.ts, src/tools/downloadUsageApiData/handler.ts, src/tools/findUnderusedResourceClasses/handler.ts, src/tools/getBuildFailureLogs/handler.ts, src/tools/getFlakyTests/handler.ts, src/tools/getJobTestResults/handler.ts, src/tools/getLatestPipelineStatus/handler.ts, src/tools/listComponentVersions/handler.ts, src/tools/recommendPromptTemplateTests/handler.ts, src/tools/rerunWorkflow/handler.ts, src/tools/runEvaluationTests/handler.ts, src/tools/runPipeline/handler.ts, src/tools/runRollbackPipeline/handler.ts
The issue appears to be in how the MCP server registers tools in `/src/index.ts`:
`{ params: tool.inputSchema.optional() }`
This makes the entire `params` object optional, so when clients call tools without parameters, `args.params` becomes `undefined`.
`const { someDestructuredVal } = args.params || {};`
- just added a little `= args.params || {};` action everywhere to assuage the need for destructuring optional and potentially `undefined` `args.params`.
=> fix: potential fix for #126 `= args.params || {};`
